#nginx-reverseproxy.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app:  nginx-reverseproxy
  name: nginx-reverseproxy-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-reverseproxy
    spec:
      containers:
      - image: nginx:1.13
        name: kubecont-nginx
        ports:
        - containerPort: 80 
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d     
      volumes:
        - name: config-volume
          persistentVolumeClaim:
           claimName: nginx-pv-claim
